- src/eval.jl
Very minor change, but displaying the module dropdown in alphabetical order fits better with other dropdowns such as the language picker. Thoughts?
> Sort modules.

- src/comm.jl
This shouldn't strictly be necessary, but is a workaround for JuliaLang/julia#10615
> adds a mutex lock around the socket println. fixes #3

- src/eval.jl
This change essentially ensures that the output of `@__FILE__` is correct. As an important side effect, the `include` function now works as it does when loading the file the first time – i.e. it loads files relative to the current file's directory.
> Use correct paths for include etc.

- src/display/objects.jl
and a minor comsetic fix for large vectors.
This works towards fixing https://github.com/JunoLab/atom-julia-client/issues/54, but I would much prefer a more general solution to this problem.
> better rendering of large Dicts

- src/eval.jl
make error notifications sticky (must be closed by the user) when evaluating a file
> sticky errors

- src/display/display.jl
- src/display/errors.jl
- src/eval.jl
So yeah, this not only sends the richly rendered results back to Atom, but some plaintext as well. The extra overhead is of course not desirable, but shouldn't be too bad.
I did try reconstructing a  plain-text result from the html-result we already have in Atom, but that is quite a lot of work if want to do it with standardized methods. 
If not, we could just clone the result-`node`, set all descendents to be visible and use [`node.innerText`](https://developer.mozilla.org/en-US/docs/Web/API/Node/innerText). This would of course mean that we wouldn't have to transmit any extra data and also would get the exactly the same representation as in Atom. Note, however, that when lazy-loading of complete arrays lands (hopefully soonish :)) this wouldn't work as intended any more and we'd need …
> julia-side support for copyable plaintext results

- src/display/errors.jl
by splitting them on `\n` and only displaying the first line in the header. 
Example: 
```julia
Vector(AbstractString,4)
#ERROR: MethodError: `convert` has no method matching convert(::Type{Array{T,1}}, ::Type{AbstractString}, ::Int64)
#This may have arisen from a call to the constructor Array{T,1}(...),
#since type constructors fall back to convert methods.
````
> Correctly render errors with multiline header

- src/display/objects.jl
Fix for https://github.com/JunoLab/atom-julia-client/issues/44.
Since we aren't doing any special rendering with arrays, they work anyway. It would be really cool to have this work for arbitrary arrays, but I couldn't figure out how to do that without constructing an array of the same size as the array to be printed right now.
So when we implement nice Array printing, this should be overhauled.
Also: Right now undef elements are printed as `"#undef"`, but that's only a small cosmetic problem, methinks.
> Handle undef entries in vectors

- src/display/objects.jl
- src/eval.jl
This is the Julia side for supporting docs-at-a-keystroke in Atom.
> Add handlers and renderers for docs and methods

- REQUIRE
if they're being directly used, they should be directly depended on,
rather than assuming they will be present as transitive deps of other packages
> add MacroTools and Requires explicitly to REQUIRE

- src/display/objects.jl
~~Short~~ design question: How do we want to handle different "rendering styles"?
Problem:
When rendering documentation in either a `Result > Tree > Children` or in a `InlineDoc` element, I don't want to create a `Tree` or `SubTree` for multiline Markdown but rather render the whole thing. But when rendering it inline, i.e. as a toplevel result, I want the implementation proposed here and create a `Tree`.
We should probably just create a new type and specialize our rendering methods on that to get that behaviour -- first I was thinking of something like `Underline`, but maybe something like `Verbose` fits better? 
If we do this, how would it integrate with the rest of the display system on the Julia side?
> inline markdown rendering

- src/eval.jl
This avoids a deprecation warning.
> symbol -> Symbol to avoid deprecation warning

- src/display/errors.jl
Always scrolling to the right to find the line info in the error box gets a bit tedious. For interactive use like in Atom I believe that showing all the types that go into the functions in the backtrace is overkill. It is simple to click the link and look at the actual function if one wants to.
> RFC: hide function argument types in backtrace

- src/Atom.jl
- src/comm.jl
- src/debugger/entry.jl
- src/debugger/load.jl
- src/debugger/mockingbird.jl
- src/eval.jl
- src/frontend.jl
- src/precompile.jl
- src/utils.jl
I've made several changes which improve Julia's boot time in Juno:
* Improve load time of various dependencies
* Lazy load gallium (obviously this cost must still be paid, which slows down first use)
* Do more precompilation
* Reduce the required negotiation by using julia-as-client locally
The median boot time is now about 3s on my laptop. For more we most likely need to expand the amount of pre-compilation done in other packages.
> Improve startup time

- REQUIRE
for where syntax to work, shouldn't claim to support early dev versions
> use 0.6.0-pre as julia lower bound

- REQUIRE
This actually works without any changes in code, since Gallium and ASTInterpreter always were loaded dynamically; the code that does this checks the Julia version, so we can't get a "missing package" warning from this.
Fixes https://github.com/JunoLab/Atom.jl/issues/91.
> remove dependency on gallium and astinterpreter

- src/display/errors.jl
- src/utils.jl
Stackframes that point to base functions are dimmed, those from packages are slightly brighter and those from user code (everything not in `Pkg.dir()` or `base`) are brightest.
Inspired by https://github.com/JuliaLang/julia/issues/22653.
Needs https://github.com/JunoLab/atom-julia-client/pull/368.
> location-dependent stackframe shading

- src/eval.jl
When a package defines a display for a certain type via `Media.media`, that internally calls something like `@eval media(...)`; right after that it's impossible to call any `render` methods, because of world age issues. 
Example would be something like `using Plots; plot([1,2,3])`, which only properly works on the subsequent call to `plot()`.
Together with https://github.com/JuliaPlots/Plots.jl/pull/916 (and https://github.com/JunoLab/atom-ink/pull/139, I guess) this makes the Plots.jl experience much nicer.
> Call invokelatest on `render` and `media`

- src/display/errors.jl
also better rendering of constructors in backtraces.
Before:
After:
~~Fixes https://github.com/JunoLab/atom-julia-client/issues/374~~.
> reverse backtrace-reversion

- src/repl.jl
This allows using Plots.jl (and presumably other plotting packages) in the new REPL-based console together with the plotpane, but unfortunately doesn't yet take plotpane size into account. I'm not sure how to best handle that, but thought I'd throw this out there and hope someone has a good idea.
cc @MikeInnes and @ChrisRackauckas
> Use base display system for plots in repl

- src/display/base.jl
I wanted to use nested `OrderedDict`, but was missing the nice drop down display of the `Dict`. I think this same method should be fine for any `AbstractDict` with this minor change.
Before:
After:
> render all AbstractDict as a Tree

- src/completions.jl
Needs https://github.com/JunoLab/atom-julia-client/pull/492.
What we gain: 
- Completions for dict keys
- Completions for pathcompletions in strings
- Completions for struct field access
- Completion hints for methods (with inferred return type and method specific docstrings):
What we lose:
- Fuzzy completions
- Performance on first call
> WIP: switch to using REPLCompletions.complete

- REQUIRE
- src/Atom.jl
- src/debugger/breakpoints.jl
- src/debugger/debugger.jl
- src/debugger/load.jl
- src/debugger/stepper.jl
- src/profiler/traceur.jl
- src/repl.jl
- src/workspace.jl
Needs https://github.com/JunoLab/atom-julia-client/pull/554 and https://github.com/JunoLab/atom-ink/pull/193.
> Compatibility with Debugger.jl

- Project.toml
- src/Atom.jl
Improves `openFile` messaging:
- Don't cause error when `InteractiveUtils.edit` gets called with non-Julia files: This is actually a bug
- Now we can open non-Julia files: Why `abspath` is introduced
> Fix open file

- src/completions.jl
https://julialang.slack.com/archives/C7JT7HQAD/p1564337316096500
Basically this enables descriptions for non-exported methods of modules and keywords: E.g.:
- `Juno.@trace`, `Atom.handle` (even in `Main`)
- `begin`, ...
> Enhance autocompletions

- src/datatip.jl
I would like to drop method tables in datatip, since it would look rather verbose and useless since atom-ide-ui/datatip can't handle links in `markedStrings` anyways.
> Drop methodtable in datatip

- src/repl.jl
Avoid error:
```
Julia Client – Internal Error
type Nothing has no field current_mode
getproperty(::Any, ::Symbol) at sysimg.jl:18
#changeREPLprompt#167(::Symbol, ::Bool, ::Function, ::String) at repl.jl:111
changeREPLprompt at repl.jl:102 [inlined]
(::getfield(Atom, Symbol("##157#158")))(::String) at repl.jl:23
handlemsg(::String, ::String) at comm.jl:164
(::getfield(Atom, Symbol("##19#21")){Array{Any,1}})() at task.jl:259
```
(Just for those who use the `consoleOptions.terminal` setting)
> Avoid error on `changeREPLprompt` on REPL startup

- src/completions.jl
- Ref: https://julialang.slack.com/archives/C7JT7HQAD/p1565114009249700
In short, I want to suppress too many completions from texts like `[|`, `(|`, or `&|` (where `|` represents cursor position), since those over 1000 completions often takes much time and worsen coding experience.
I think it would be better if we could handle these cases in front end (i.e. atom-julia-client) in terms of efficiency, but I found the corner cases can be a lot and handling them in backend like this is fairly easy and simple.
> Better completions

- src/completions.jl
- src/debugger/stepper.jl
- src/docs.jl
- src/workspace.jl
addressing: https://github.com/JunoLab/atom-julia-client/blob/master/lib/runtime/completions.js#L4
- we basically use `wstype` and `wsicon` for all the type/icon definitions of workspace/completions/docs
* simplify code a lot
* special cases like `keyword` and workspaces in debugger are gracefully handled, I believe
- all these tasks are handled by backend, which makes code simpler I believe
- introduced constant-ness check for all of them: every objects has either `variable` or `constant` type
- added some additional icon definitions for `Regex` and so
corresponding PRs:
- https://github.com/JunoLab/atom-julia-client/pull/592
- https://github.com/JunoLab/atom-ink/pull/213
> consistent types

- src/completions.jl
- src/docs.jl
- src/workspace.jl
handles undefined in workspace so that package developers can easily find the no more defined exports: e.g.:
And as for completions, including undefs in comoletions is what REPL completion does and so it would be more consistent.
> Handle undefined

- Project.toml
It's probably better not to promise compatibility with Julia 2+
> Enforce compatibility with julia 1

- src/debugger/breakpoints.jl
- src/debugger/stepper.jl
- add different prompt color for compiled mode
- enable basic REPL completions in debugger REPL
we may enhance more, by enabling local completions as well (using the same logic as workspace)
***
additionally, I would like to add debugger commands that are accessible from debugger REPL like [Debugger.jl's interface](https://github.com/JuliaDebug/Debugger.jl#debugger-commands), e.g.:
- entering `:nc` in the REPL will step into the next call.
I would like to hear your ideas about these commands.
> debugger enhancements

- src/completions.jl
- src/debugger/stepper.jl
- src/frontend.jl
- src/outline.jl
- src/path_matching.jl
- remove unnecessary field from DebuggerState
- type structs in outline.jl
- more const
- remove union type from `makedescription`
neither of them is slow from for now, thus the changes above wouldn't be any important tho.
> small refactors:

- src/completions.jl
- src/outline.jl
- test/completions.jl
- test/misc.jl
- don't include function arguments in outline
- stop kwargs/anon function args form leaking into outer scope
- improve locality based completion ranking by basing it on lines 
instead of the byteoffset
- give bindings defined *before* the current line a higher priority
> improve completions/outline

- src/outline.jl
- test/completions.jl
- test/misc.jl
and completions.
Fixes https://github.com/JunoLab/Atom.jl/issues/171.
> no named tuple elements in outline

- src/Atom.jl
- src/completions.jl
- src/display/base.jl
- src/display/frontend.jl
- src/docs.jl
- src/eval.jl
- src/utils.jl
- src/workspace.jl
refactor get moethods: …
- define getter methods in one place: utils.jl
- add type annotation and docs for better development
- `getfield′` now uses `CodeTools.getthing`
* e.g.: #173 will be able to handle `Atom.handlers` in `Atom` module
getmodule′ -> getmodule:
> refactors around `get` methods

- src/eval.jl
- test/eval.jl
A method definition with default arguments introduces different method instances, but they are better to be handled as an unique method in terms of "goto method", since their definition location is exactly same, and otherwise they might appear verbose.
- the methods with full arguments are going to be shown as a representative of the other _incomplete_ methods
- Tests are added.
> aggregate methods with default args within goto

- src/debugger/stepper.jl
imho this would make workspace view in debugging more intuitive
- the more recent values are (first) interpreted, the upper they would appear:
- consistent with how the function callstacks are ordered
> reverse workspace stack in debugging

- src/Atom.jl
- src/repl.jl
First I tried to enable this feature via https://github.com/JuliaLang/julia/pull/33102, but the PR would take more time to be finished I think, and so I want to _partly_ realise that here:
Pros:
- we can get module-aware completions within the integrated REPL
Cons:
- an user can no longer has their own custom `complete` within Juno: it's automatically updated by each call of `changemodule`
- help mode is still not module-aware (that's why this feature is still "partly" realised)
Alternative design:
- if we use an weird global `context_module` for REPL completions, then we can attach our custom completion provider on `atreplinit`, and then it would allow an user's custom `complete`
> enhance completions within the integrated REPL

- src/display/showdisplay.jl
- src/frontend.jl
Needs https://github.com/JunoLab/atom-julia-client/pull/609 to do something useful, but will work regardless.
> make plots devicePixelRatio aware

- src/debugger/datatip.jl
- src/debugger/debugger.jl
- src/debugger/repl.jl
- src/debugger/stepper.jl
- src/debugger/workspace.jl
Mainly I did two things on this branch:
1. separate stepper.jl into appropriate sub files (since stepper.jl's got so fat)
2. enable "complete" completions within debug REPL: e.g.:
* `MethodCompletion` including local bindings: `strlimit(localstring, |` should show `MethodCompletion`s for `strlimit(str::String, ...)`
* `PropertyCompletion` for local bindings: `localobj.|` should show the properties of `localobj`
* etc...
A part that needs to be reviewed is obviously around 2 -- it's doing [such a hacky/dirty thing](https://github.com/JunoLab/Atom.jl/blob/01c215ba246e9c0d3a159b045b829f0533d8a9bf/src/debugger/debugger.jl#L26-L67) (overwriting the methods within REPL module)
This implementation is not so robust to future changes within `REPLCompletion` module, but imho I suspect we can detect …
> debugger refactors

- src/display/base.jl
Fixes https://github.com/JunoLab/Juno.jl/issues/371.
> different vector/set/dict head render

- src/outline.jl
- test/outline.jl
fixes https://github.com/JunoLab/Juno.jl/issues/374
> stringify method signatures with keyword args correctly

- src/completions.jl
- src/utils.jl
- test/completions.jl
- simplify the whole logic in `completion(mod, c)`
- `returntype` -> `completionreturntype`
- enhance `DictCompletion`
* show value type
* add icon/type
- enhance `FieldCompletion`
* show a predicted type in rightLabel
- fix the logic `completiontext(::MethodCompletion)` for a case when the regex does not match
- `shortstr` function
- move `cangetdocs` into utils.jl
- don't use `handle` in tests
- add more test cases
> more refactors on completions.jl

- src/display/methods.jl
Fixes https://github.com/JunoLab/Atom.jl/pull/189.
> no custom method sorting

- src/display/errors.jl
- src/eval.jl
and add an option to always show errors in REPL when using inline evaluation.
Fixes https://github.com/JunoLab/Juno.jl/issues/381.
> improve error printing

- src/utils.jl
`isdir` can error when the user doesn't have read access to `basebuilddir`, and afaict the code to build that const isn't really necessary anyways (or at least noone has complained about our `basepath` implementation).
> re-use `basepath` for getting path to julia install

- src/outline.jl
- test/outline.jl
A `where` clause creates `LocalScope`, which holds method arguments as its children, but `_actual_local_bindings` fails to enter into its children on https://github.com/JunoLab/Atom.jl/blob/1f9cf9db6020a84a5b7430850d2cd8c9bf1cd35c/src/outline.jl#L303
Fixes via the same approach as https://github.com/JunoLab/Atom.jl/pull/183
> fixes JunoLab/Juno.jl#404

- src/completions.jl
- src/docs.jl
- src/utils.jl
- src/workspace.jl
- test/utils.jl
- create methods for uri-handler
- add is-utilities and tests
- more docs on util methods
***
Separated from #203 for easier review
> better utils:

- src/datatip.jl
- src/display/methods.jl
- src/goto.jl
- src/utils.jl
- test/datatip.jl
- test/goto.jl
- test/utils.jl
While implementing #203, I had to implement the logic to remove trailing dots and found that this is better to be merged as a separate feature, since the logic can be used for goto/datatip.
In short, if we have a word like
```jl
Atom.SYMBOLSCACHE.age
```
and then, we can get goto and datatip for:
- `Atom` when our cursor is anywhere on `Atom`
- `Atom.SYMBOLSCACHE` when our cursor is anywhere on `SYMBOLSCACHE`
- no datatip if our cursor is on `age` (the field)
(c.f.: The current behaviour: we can't get any goto and datatip at all)
***
Requires https://github.com/JunoLab/atom-julia-client/pull/651
> strip trailing dots in goto/datatip (and rename)

- src/Atom.jl
- src/goto.jl
- src/modules.jl
- src/outline.jl
- src/static/static.jl
- src/static/toplevel.jl
- src/utils.jl
- test/completions.jl
- test/datatip.jl
- test/fixtures/Junk.jl
- test/fixtures/SubJunks.jl
- test/goto.jl
- test/modules.jl
- test/outline.jl
- test/runtests.jl
- test/static/static.jl
- test/static/toplevel.jl
- test/workspace.jl
fixes module escaping issues within CSTPraser-based module traverse
That would make goto and rename refactors (https://github.com/JunoLab/Atom.jl/pull/203) more "correct", and may also help https://github.com/JunoLab/Juno.jl/issues/411.
I also included changes that enables gotos within unsaved editors
> RFC: module validation check within CSTParser-based module traverse

- src/goto.jl
- src/modules.jl
- src/outline.jl
- src/static/local.jl
- src/static/static.jl
- src/static/toplevel.jl
- test/goto.jl
- test/outline.jl
Don't let `SYMBOLSCACHE` eat memory like a horse -- now it only uses`4 MiB` after `julia-client: regenerate-symbol-cache` while it did `140 MiB` within the previous implementation.
refactors:
- only keep _simple_ data in `SYMBOLSCACHE`
- remove `ToplevelTupleH` struct: make the overall code much simpler
> more memory efficient SYMBOLSCACHE

- src/goto.jl
- src/outline.jl
- src/static/local.jl
- src/static/static.jl
- src/static/toplevel.jl
- test/outline.jl
create `ToplevelModuleUsage` struct and shows them in outline:
we may want to use them in modules.jl or goto.jl as well for more precise module traverse in the future
***
First I would like to merge #219 and the rebase this PR.
> outline module usages

- src/completions.jl
- src/utils.jl
- test/completions.jl
needs https://github.com/JunoLab/atom-julia-client/pull/663
***
A profiling on `basecompletionadapter` shows [`completionsummary`](https://github.com/JunoLab/Atom.jl/blob/master/src/completions.jl#L108-L126) took much time -- this is obvious because retrieving a doc string is done by calling [`include_string` in `getdocs`](https://github.com/JunoLab/Atom.jl/blob/avi/optimcomps/src/utils.jl#L217-L234).
As a consequence, sometimes I can't get completions because of [the racing in frontend](https://github.com/JunoLab/atom-julia-client/blob/avi/optimcomps/lib/runtime/completions.js#L50) (which is good thing though) when there are many of suggestion (say, >100).
So I would like to simply suppress them when there are so many of completion suggestions, because I guess showing completion …
> RFC: improve completion performance

- src/misc.jl
- src/utils.jl
- test/goto.jl
- test/modules.jl
- test/runtests.jl
- test/utils.jl
Enables `julia-client: activate-environment-in-current-folder` command to work when invoked from any dir under the `Project.toml` file
> recursive Project.toml search

- Project.toml
- src/static/bindings.jl
- src/static/local.jl
- src/static/scope.jl
- src/static/static.jl
- src/static/toplevel.jl
- test/datatip.jl
- test/goto.jl
- test/static/bindings.jl
- test/static/local.jl
- test/static/static.jl
Fixes #226 .
Previous tests are almost never modified and so we now can update CSTParser while keeping all the functionalities we've implemented.
The basic binding test is added.
Later I'll add a small fix related to #223 .
TODO:
> update to latest CSTParser

- src/completions.jl
- src/datatip.jl
- src/goto.jl
- src/modules.jl
- src/outline.jl
- src/static/local.jl
- src/static/static.jl
- src/static/toplevel.jl
- test/goto.jl
- test/outline.jl
- test/runtests.jl
- test/static/local.jl
general:
- more preferable naming
goto:
- recover goto for unloaded packages (can be invoked via docpane)
outline:
- introduce `ActualLocalBinding` struct
- minimum condition check for `toplevelitems`
- show `__precompile__` calls in outline
Needs https://github.com/JunoLab/atom-julia-client/pull/681
> refactor static features

- src/completions.jl
- test/completions.jl
- Show return types for all the method completions
* revert back some part that was introduced in #234 
* I found revealing a return type on selection is not natural since all the `leftLabel` of suggestions are visible
* first time method completion invocation is reverted back to be slow, though.
- Now return types can be inferred from input types, while we only used method signature in the previous implementation. Now we can infer return type for more completion cases.
* E.g.: If we have `f(a) = a`, within the previous behaviour we can't infer in any completion case. With this PR we can show return types if there is input arguments:
+ `f(1|` => inferred as `Int`
+ `f('1'|` => inferred as `Char`
> moar return types:

- src/docs.jl
- test/docs.jl
The main change is to improve documentation searches where the needle is like `Mod.needle`.
If `Mod` is available, this would automatically search `needle` in `Mod` module (the same logic as https://github.com/JunoLab/Atom.jl/pull/208)
This would overwrites an user's module specification (if specified),
(e.g.:
would overwrite `Atom.JunoDebugger` spec to `JuliaInterpreter`)
but I believe that would be more preferable for reasons:
- an user intentionally type module prefix for these cases
- some documentation references includes module prefixes and they don't work as expected with the previous behaviour:
* e.g: https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/master/src/construct.jl#L353
***
I also added some tests for this and other.
> RFC: better documentation search

- src/Atom.jl
- src/repl.jl
- no spurious error when hideprompt is called before we have registered 
our own on_done handler
- keep zero-width spaces out of repl history
Fixes https://github.com/JunoLab/Juno.jl/issues/487.
> fix hide prompt issues

- src/display/showdisplay.jl
instead of `escapeuri`ing them.
This provides a 50x speedup...
> base64 encode data uris

- src/goto.jl
Can happen when we switched to a branch where a certain file for a already loaded module doesn't exist, etc.
> file existence check for Revise-like module traverse

- .travis.yml
so that we don't need to bump Julia versions until the next LTS/major version release
> bump travis Julia versions

- test/completions.jl
Skipped when https://github.com/JunoLab/Atom.jl/pull/225 was introduced, but it's not actually broken.
> no skip path completion test

- Project.toml
- src/Atom.jl
- src/profiler/traceur.jl
- test/modules.jl
- test/runtests.jl
Since Traceur is still in alpha (and currently has problems in its performance and robustness), I believe ppl don't use this integration so much that it might be okay that it's not provided by default.
Although Traceur (and Cassette) dependency isn't so heavy, but will improve the loading time for sure.
> lazy Traceur loading

- src/utils.jl
Hide errors for e.g. PyPlot:
```
using PyPlot
fig = figure()
ax = subplot(211)
ax#<tab>
```
> try catch in getdocs

- src/eval.jl
to make sure we call the right show methods etc
> more invokelatest's

- src/debugger/stepper.jl
- set task_local_storage for toplevel debugging
- enable "step-to-selected-line" for toplevel debugging: currently results in error
closes https://github.com/JunoLab/Juno.jl/issues/569
> toplevel debugging improvements

- src/completions.jl
- src/goto.jl
- src/outline.jl
- src/precompile.jl
- test/completions/fuzzycompletions.jl
- test/completions/replcompletions.jl
- test/goto.jl
- test/outline.jl
- test/runtests.jl
~- introduce `@tojs` macro that enables us to easily construct `NamedTuple`s and `Dict`s~
~- no more verbose `todict` conversion~
~- bit of test robustness improvements~
internal refactors:
- use `NamedTuple` instead of `Dict` where possible: more robust for typo, etc
- no more verbose `todict` conversion
- a bit test improvement
> internal refactors

- src/misc.jl
- src/precompile.jl
- use `JunoProgressLogger`
- use `include_string`
> improve `evalsimple` handler:

- src/datatip.jl
- src/display/base.jl
- src/static/local.jl
- src/static/static.jl
- src/static/toplevel.jl
- src/utils.jl
- `::Int` -> `::Integer` for 32bits system compatibility
- don't overload `Base.contlines`
> bit refactors

- src/completions.jl
- src/display/base.jl
- test/display.jl
I found `string(typeof(f).name)` returns `"typename(typeof(f))"`, which causes function display a bit weird (e.g. `sin(`) on v1.6 (at least current master)
I believe using `repr` and `string` would make the logic mach simpler and robust in the future, so this PR.
I also improved a logic in a completion a bit
> fix function display on v1.6

- src/display/base.jl
- src/display/methods.jl
Also fixes JunoLab/Juno.jl#596 by avoiding `repr` call with anonymous function.
> Informative closure rendering

- src/completions.jl
not sure why I've not noticed this until now, but `filter!(!ispkgcomp, cs)` seems to be sheer wrong; now `using WhatEverPrefixOfDependency` works as in REPL.
> fix `PackageCompletion`s

- src/utils.jl
see https://github.com/JuliaLang/julia/issues/38059 for the rationale
> fix completion performance regression on v1.6:

- src/comm.jl
With that commit, `Task` won't run in the latest global world age, so we
want to add manual `invokelatest` to dynamically update `handlers`.
> update to https://github.com/JuliaLang/julia/pull/41449
