JunoLab/Atom.jl

src/comm.jl

Sorry, I got confused, I thought the PR was directly on your repo, not mine... Hope this works better!

2nd attempt at PR for long vector display

---

src/misc.jl

to enable https://github.com/JunoLab/atom-julia-client/pull/115

add clear-workspace msg handler

---

src/eval.jl

fixes https://github.com/JunoLab/atom-julia-client/issues/177
would be great if someone could test this on something not-windows, but it *should*  work everywhere ;)

better shell exec in console

---

src/eval.jl

not sure if that change to the evaluation logic is correct, but I think it should be; also not sure if this is really desirable...

latest thing evaled in the console assigned to `ans`

---

src/display/errors.jl

Inspired by #49.
Also shows no expand arrow when there's nothing to expand to, though we could just solve that in `julia-client` and have no arrow when `children` is empty.
cc @KristofferC

various backtrace-rendering improvements

---

src/display/methods.jl

Fixes https://github.com/JunoLab/atom-julia-client/issues/214#issuecomment-240312544

remove undefined options to fix @which

---

src/comm.jl

document comm.jl

---

src/eval.jl

Editor and Console respect semi-colon at the end. 
errors are still being rendered if they occurred while evaluating

Respect semicolon

---

src/eval.jl

goto panel

---

src/Atom.jl
src/completions.jl
src/display/base.jl
src/display/display.jl
src/display/errors.jl
src/display/frontend.jl
src/display/lazy.jl
src/display/markdown.jl
src/display/methods.jl
src/display/plots.jl
src/display/utils.jl
src/display/view.jl
src/docs.jl
src/profiler/profiler.jl
src/progress.jl
src/repl.jl

ref: https://github.com/JunoLab/Juno.jl/pull/95
~~progress still broken.~~

reorganize

---

src/display/base.jl

I'm assuming that's a typo, otherwise this can be closed.

legcay -> legacy

---

src/debugger/stepper.jl

On the following test code:
```julia
f(x, y=:hello) = sum(rand(5))
g(x) = f(x)
h(x) = f(x, :hi)
```
this avoids the following error:
```julia
julia> includet("/tmp/testsym.jl")
julia> Juno.@enter g(3)   # here I stepped in to f
debug> y
ERROR: UndefVarError: hello not defined
Stacktrace:
[1] top-level scope at none:0
[2] eval at ./boot.jl:328 [inlined]
[3] eval_code(::JuliaInterpreter.Frame, ::String) at /home/tim/.julia/dev/Atom/src/debugger/stepper.jl:371
[4] interpret(::String, ::Atom.JunoDebugger.DebuggerState) at /home/tim/.julia/dev/Atom/src/debugger/stepper.jl:355
[5] interpret at /home/tim/.julia/dev/Atom/src/debugger/stepper.jl:354 [inlined]
[6] (::getfield(Atom.JunoDebugger, Symbol("##50#52")))(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at …
```

Quote symbols and expressions in eval_code

---

src/docs.jl

- `Julia Standard Library` -> `Julia Base Library`
- Render `Defined symbols` in UI font
- Correctly show `Julia Standard Library`
- Reorder function defs

tweak docs:

---

src/completions.jl
src/datatip.jl
src/docs.jl
src/workspace.jl
test/completions.jl
test/eval.jl
test/runtests.jl

I want to add tests for completions since I love that:
- Any error is handled in the parent function `basecompletionadapter`, thus without tests it would need manual testing/detection to find errors when they happen
Would like to merge https://github.com/JunoLab/Atom.jl/pull/156 first

completion test

---

src/docs.jl
src/eval.jl
src/progress.jl
src/repl.jl

by always using the current `global_logger`

better progress handling

---

src/completions.jl
src/docs.jl

- follow the naming conventions of the official docs
- suppress module information in keyword completions

small tweaks

---

src/completions.jl
src/eval.jl
src/workspace.jl
test/completions.jl
test/eval.jl
test/fixtures/Junk.jl
test/misc.jl
test/runtests.jl
test/utils.jl
test/workspace.jl

add tests for various things I want to make sure to work:
I also may want to enable codecov for Atom.jl, which may or may not encourage us to write more tests in the future, what do you think @pfitzseb ?

test, test, and test

---

src/completions.jl

can be useful for someone ?
xref: https://github.com/JunoLab/atom-julia-client/pull/601

add uri-handler for completions

---

src/debugger/stepper.jl
src/display/showdisplay.jl
src/eval.jl

Fixes https://github.com/JunoLab/Juno.jl/issues/364.
Also improves the behaviour of errors during other `render` calls (which regressed some time ago).

better display errors

---

src/comm.jl

also only warn once for each command

improve warning for unrecognised commands

---

src/misc.jl

Needs https://github.com/JunoLab/atom-julia-client/pull/646.
Fixes https://github.com/JunoLab/Juno.jl/issues/206.

activate env

---

src/modules.jl

Later I will open an issue on Revise's repo about the discussion on extracting upstream code, which would get rid of the need for these changes.

follow https://github.com/timholy/Revise.jl/pull/385

---

src/debugger/repl.jl

fixes https://github.com/JunoLab/Juno.jl/issues/430

check AST is complete in debug prompt

---

src/eval.jl
test/eval.jl
test/fixtures/EvalTest.jl
test/misc.jl
test/runtests.jl

and add a basic tests (without any kind of test for displays)

separete `eval` commands' execution body into a function

---

src/misc.jl

Now `work-in-hoge` commands would be more explicit like `activate-hoge`s :)

log `cd` handler

---

src/misc.jl

part of the fix for https://github.com/JunoLab/Juno.jl/issues/450.

access Base.ARGS directly

---

src/goto.jl
src/modules.jl
test/fixtures/mutual_recur.jl
test/fixtures/mutual_recur2.jl
test/fixtures/self_recur.jl
test/goto.jl
test/modules.jl
test/runtests.jl

escape recursive `include` loops

---

.github/workflows/CompatHelper.yml

@pfitzseb how about using compat helper since we have lots of dependencies ?

compat helper

---

src/debugger/stepper.jl

prettier current code rendering for frames in unsaved editor

---

src/completions.jl
test/.gitignore
test/completions.jl

Yesterday I found the vscode extension shows this :)

show local completion description

---

scripts/.gitignore
scripts/generate_precompile.jl
src/precompile.jl
test/workspace.jl

Not sure why the workspace tests fail _only_ when run while generating the precompile statements...

try catch in _precompile_

---

.travis.yml

Tests are failing on 1.0, for now add testing on 1.1 only

test package on julia 1.1

---

src/repl.jl

Needs https://github.com/JunoLab/atom-julia-client/pull/694.

more prompt fixes

---

src/repl.jl

Fixes https://github.com/JunoLab/Juno.jl/issues/500.

try harder to break out of repl modes

---

src/eval.jl
src/progress.jl
src/repl.jl

Fix for custom loggers

---

src/repl.jl

Fixes https://github.com/JunoLab/Juno.jl/issues/526 and related issues.

even more "robust" hideprompt

---

src/display/base.jl

Fixes https://github.com/JunoLab/Juno.jl/issues/535.

fix functor display

---

src/display/base.jl

fixes https://github.com/JunoLab/Juno.jl/issues/535

improvements on function displays:

---

src/eval.jl

Fixes https://github.com/JunoLab/Juno.jl/issues/541.

fix plots for terminal results

---

src/formatter.jl

once we've done https://github.com/domluna/JuliaFormatter.jl/issues/184, we will no longer need this kind of update

allow more JuliaFormatter options

---

src/utils.jl

use Base.DATAROOTDIR for base path search

---

src/frontend.jl

corresponds to:
-  https://github.com/JunoLab/atom-julia-client/pull/743
- https://github.com/JunoLab/Juno.jl/pull/577

remove unused messenger and add new notification messenger

---

src/completions.jl

will fix test failures on the latest julias

update to latest type inference

---

src/debugger/stepper.jl

Fixes https://github.com/JunoLab/Juno.jl/issues/599 (I think).

fix stepper display

---

src/modules.jl
src/utils.jl

makes it easy to work within `Core.Compiler`

special case `Core.Compiler` module detection
